[package]
name = "sqlx_migrator"
version = "0.8.0"
edition = "2021"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/sqlx_migrator"
repository = "https://github.com/iamsauravsharma/sqlx_migrator"
description = "Migrator for writing sqlx migration using Rust instead of SQL"
license = "MIT"
readme = "README.MD"
keywords = ["sqlx", "sqlx_migrations", "rust_migrations"]
categories = ["database"]

[dependencies]
sqlx = { version = "0.7.0", default-features = false, features = [
    "macros",
    "chrono",
] }
async-trait = "0.1.70"
tracing = { version = "0.1.37", optional = true }
thiserror = "1.0.41"
clap = { version = "4.3.10", features = ["derive"], optional = true }
chrono = { version = "0.4.26", default-features = false, features = ["std"] }
crc32fast = { version = "1.3.2", optional = true }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }

[features]
default = ["cli", "tracing"]
tracing = ["dep:tracing"]
postgres = ["sqlx/postgres", "dep:crc32fast"]
sqlite = ["sqlx/sqlite"]
mysql = ["sqlx/mysql", "dep:crc32fast"]
any = ["sqlx/any"]
cli = ["dep:clap"]
runtime-async-std = ["sqlx/runtime-async-std"]
runtime-tokio = ["sqlx/runtime-tokio"]
tls-native-tls = ["sqlx/tls-native-tls"]
tls-rustls = ["sqlx/tls-rustls"]

[[example]]
name = "postgres"
path = "examples/postgres/main.rs"
required-features = ["postgres", "cli"]

[[example]]
name = "sqlite"
path = "examples/sqlite/main.rs"
required-features = ["sqlite", "cli"]

[[example]]
name = "mysql"
path = "examples/mysql/main.rs"
required-features = ["mysql", "cli"]

[package.metadata.docs.rs]
features = ["postgres", "sqlite", "mysql", "any", "runtime-tokio", "tls-rustls"]
rustdoc-args = ["--cfg", "docsrs"]
